docker-server]
docker_soft ansible_host=localhost ansible_connection=local
[harbor-server]
harbor_soft ansible_host=localhost ansible_connection=local
[vault-server]
vault_soft ansible_host=localhost ansible_connection=local
[kubernetes-server]
kubernetes_soft ansible_host=localhost ansible_connection=local


